server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:security-basics
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
jwt:
  secret: 12345
  expiry: 100000
  refresh:
    expiry: 10000000